import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import styles from '~/styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/examples/emotion/">
            <a className={styles.card}>
              <h2>Emotion example &rarr;</h2>
              <p>This is emotion example page link.</p>
            </a>
          </Link>

          <Link href="/examples/recoil/">
            <a className={styles.card}>
              <h2>Recoil example &rarr;</h2>
              <p>This is recoil example page link.</p>
            </a>
          </Link>

          <Link href="/examples/graphql/">
            <a className={styles.card}>
              <h2>GraphQL example &rarr;</h2>
              <p>This is GraphQL example page link.</p>
            </a>
          </Link>
          <Link href="/examples/calendar/">
            <a className={styles.card}>
              <h2>Calendar example &rarr;</h2>
              <p>This is Calendar example page link.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
