import { css } from '@emotion/css'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div
      className={css`
        padding: 0 2rem;
      `}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={css`
          min-height: 100vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        `}
      >
        <h1
          className={css`
            margin: 0;
            line-height: 1.15;
            font-size: 4rem;
            text-align: center;
            a {
              color: #0070f3;
              text-decoration: none;
              &:hover,
              &:focus,
              &:active {
                text-decoration: underline;
              }
            }
          `}
        >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p
          className={css`
            margin: 4rem 0;
            line-height: 1.5;
            font-size: 1.5rem;
            text-align: center;
          `}
        >
          Get started by editing
          <code
            className={css`
              background: #fafafa;
              border-radius: 5px;
              padding: 0.75rem;
              font-size: 1.1rem;
              font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
                Bitstream Vera Sans Mono, Courier New, monospace;
            `}
          >
            pages/index.tsx
          </code>
        </p>

        <div
          className={css`
            display: flex;
            align-items: center;
            justify-content: center;
            flex-wrap: wrap;
            max-width: 800px;
            @media (max-width: 600px) {
              width: 100%;
              flex-direction: column;
            }
          `}
        >
          <Link href="/examples/emotion/">
            <a className={cssCard}>
              <h2>Emotion example &rarr;</h2>
              <p>This is emotion example page link.</p>
            </a>
          </Link>

          <Link href="/examples/recoil/">
            <a className={cssCard}>
              <h2>Recoil example &rarr;</h2>
              <p>This is recoil example page link.</p>
            </a>
          </Link>

          <Link href="/examples/graphql/">
            <a className={cssCard}>
              <h2>GraphQL example &rarr;</h2>
              <p>This is GraphQL example page link.</p>
            </a>
          </Link>
          <Link href="/examples/calendar/">
            <a className={cssCard}>
              <h2>Calendar example &rarr;</h2>
              <p>This is Calendar example page link.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer
        className={css`
          display: flex;
          flex: 1;
          padding: 2rem 0;
          border-top: 1px solid #eaeaea;
          justify-content: center;
          align-items: center;
          a {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-grow: 1;
          }
        `}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span
            className={css`
              height: 1em;
              margin-left: 0.5rem;
            `}
          >
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

const cssCard = css`
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  max-width: 300px;
  &:hover,
  &:focus,
  &:active {
    color: #0070f3;
    border-color: #0070f3;
  }
  h2 {
    margin: 0 0 1rem 0;
    font-size: 1.5rem;
  }
  p {
    margin: 0;
    font-size: 1.25rem;
    line-height: 1.5;
  }
`
