fragment UserFields on users {
  id
  name
  birthday
}

query users {
  users {
    ...UserFields
  }
}

subscription subscribeUsers {
  users {
    ...UserFields
  }
}

mutation createUser($name: String, $birthday: timestamptz) {
  insert_users(objects: [{ name: $name, birthday: $birthday }]) {
    affected_rows
  }
}
